version: '2'
services:
  browser:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    container_name: juice-nginx
    volumes:
      - /root/joker_page://usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf